### ISSUE TITLE
Error immediately when running levellistresolver Synthesis script

### ISSUE THREAD

**Issue by technicallyJack** [OddDrifter/leveledlistresolver#5]
I get the below stack trace when running this script against my load order, through MO2. Not sure if it's a me problem, but leaning to not because it's for Update.esm.

```Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Report issues at https://github.com/OddDrifter/leveledlistresolver/issues
RecordException  => TS_FurnitureCommonClothes70 (A10801:Update.esm<LeveledItem>): Unexpected record encountered: LVLI. Was expecting: LVLO, COED System.ArgumentException: Unexpected record encountered: LVLI. Was expecting: LVLO, COED
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.ParseRecordLocationsByCount(OverlayStream stream, UInt32 count, ICollectionGetter`1 trigger, RecordHeaderConstants constants, Boolean skipHeader)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.BinaryOverlayList.FactoryByCountPerItem[T](OverlayStream stream, BinaryOverlayFactoryPackage package, Int32 countLength, ICollectionGetter`1 subrecordType, RecordType countType, RecordTypeConverter recordTypeConverter, SpanRecordFactory`1 getter, Boolean skipHeader)
   at Mutagen.Bethesda.Skyrim.Internals.LeveledItemBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, Nullable`1 lastParsed, Dictionary`2 recordParseCount, RecordTypeConverter recordTypeConverter)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, RecordTypeConverter recordTypeConverter, RecordTypeFillWrapper fill)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(IMajorRecordCommonGetter majorReference, OverlayStream stream, Int32 finalPos, Int32 offset, RecordTypeConverter recordTypeConverter, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Plugins.Records.Internals.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.EnumerateMajorRecordContexts(ISkyrimModGetter obj, ILinkCache linkCache, Type type, Boolean throwIfUnknown)+MoveNext()
   at Mutagen.Bethesda.Cache.Implementations.ImmutableLoadOrderLinkCacheContextCategory`3.<ResolveAllContexts>g__AddRecords|7_0(TModGetter mod, Type type, <>c__DisplayClass7_0& )
   at Mutagen.Bethesda.Cache.Implementations.ImmutableLoadOrderLinkCacheContextCategory`3.ResolveAllContexts(K key, Nullable`1 modKey, Type type)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Mutagen.Bethesda.Cache.Implementations.MutableLoadOrderLinkCache`2.ResolveAllContexts[TMajor,TMajorGetter](FormKey formKey, ResolveTarget target)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other)
   at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 equalityComparer)
   at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource](IEnumerable`1 source)
   at leveledlistresolver.Utility.CountExtents[TMajor,TMajorGetter](IPatcherState`2 state, FormKey& formKey) in C:\Users\jacks\AppData\Local\Temp\Synthesis\qhajvyxr.55g\Git\fjens0jv.zoi\Runner\leveledlistresolver\Utility.cs:line 97
   at leveledlistresolver.Patcher.<>c__DisplayClass4_0.<Apply>b__0(ILeveledItemGetter form) in C:\Users\jacks\AppData\Local\Temp\Synthesis\qhajvyxr.55g\Git\fjens0jv.zoi\Runner\leveledlistresolver\Patcher.cs:line 41
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at leveledlistresolver.Patcher.Apply(IPatcherState`2 state)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)```

**Comment by OddDrifter** [comment]
Can you share your load order?

**Comment by technicallyJack** [comment]
[LoadOrder.txt](https://github.com/OddDrifter/leveledlistresolver/files/7018226/LoadOrder.txt)

**Comment by technicallyJack** [comment]
I found my problem child which makes sense, I suppose. Sorry for the confusion! I honestly had forgotten I had that one in there until I started doing my disable by binary search method today. Cheers.
[Containers and Leveled Lists Fixes - Complete Loot Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/26575)
