### ISSUE TITLE
Issue with lore friendly Rifles of Skyrim

### ISSUE THREAD

**Issue by sourheadORIGIN** [OddDrifter/leveledlistresolver#6]
I don't know what any of this mean I'm just reporting the error. 

Report issues at https://github.com/OddDrifter/leveledlistresolver/issues
SubrecordException  => 0_LootBanditBulletss (00085B:HandgunsOfSkyrim.esp) => LLCT: Unexpected record encountered: LVLI. Was expecting: LVLO, COED System.ArgumentException: Unexpected record encountered: LVLI. Was expecting: LVLO, COED
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.ParseRecordLocationsByCount(OverlayStream stream, UInt32 count, ICollectionGetter`1 trigger, RecordHeaderConstants constants, Boolean skipHeader)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.BinaryOverlayList.FactoryByCountPerItem[T](OverlayStream stream, BinaryOverlayFactoryPackage package, Int32 countLength, ICollectionGetter`1 subrecordType, RecordType countType, Nullable`1 parseParams, SpanRecordFactory`1 getter, Boolean skipHeader)
   at Mutagen.Bethesda.Skyrim.Internals.LeveledItemBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, PreviousParse lastParsed, Dictionary`2 recordParseCount, Nullable`1 parseParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, Nullable`1 parseParams, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Plugins.Records.Internals.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.EnumerateMajorRecordContexts(ISkyrimModGetter obj, ILinkCache linkCache, Type type, Boolean throwIfUnknown)+MoveNext()
   at Mutagen.Bethesda.Plugins.Cache.Internals.Implementations.Internal.ImmutableLoadOrderLinkCacheContextCategory`3.<ResolveAllContexts>g__AddRecords|11_0(TModGetter mod, Type type, <>c__DisplayClass11_0& )
   at Mutagen.Bethesda.Plugins.Cache.Internals.Implementations.Internal.ImmutableLoadOrderLinkCacheContextCategory`3.ResolveAllContexts(TKey key, Nullable`1 modKey, Type type)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Mutagen.Bethesda.Plugins.Cache.Internals.Implementations.MutableLoadOrderLinkCache`2.ResolveAllContexts[TMajor,TMajorGetter](FormKey formKey, ResolveTarget target)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other)
   at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 equalityComparer)
   at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource](IEnumerable`1 source)
   at leveledlistresolver.Utility.CountExtents[TMajor,TMajorGetter](IPatcherState`2 state, FormKey& formKey) in C:\Users\rusty\AppData\Local\Temp\Synthesis\2nc0bsyb.umf\Git\ooq1isba.min\Runner\leveledlistresolver\Utility.cs:line 97
   at leveledlistresolver.Patcher.<>c__DisplayClass4_0.<Apply>b__0(ILeveledItemGetter form) in C:\Users\rusty\AppData\Local\Temp\Synthesis\2nc0bsyb.umf\Git\ooq1isba.min\Runner\leveledlistresolver\Patcher.cs:line 41
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at leveledlistresolver.Patcher.Apply(IPatcherState`2 state)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(ModKey outputKey, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, String persistencePath)

**Comment by OddDrifter** [comment]
This is happening because a few of the leveled lists in the plugin have incorrect counts. This is an issue that can really only be solved by the mod author.

**Comment by sourheadORIGIN** [comment]
thank you I'll let the mod creator know.
